name: RidgeToReef
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.13=py36_0
  - cython=0.28.5=py36h0a44026_0
  - intel-openmp=2018.0.3=0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - ncurses=6.1=h0a44026_0
  - numpy=1.15.0=py36h648b28d_0
  - numpy-base=1.15.0=py36h8a80b8c_0
  - openssl=1.0.2p=h1de35cc_0
  - pip=10.0.1=py36_0
  - python=3.6.6=hc167b69_0
  - readline=7.0=hc1231fa_4
  - setuptools=40.0.0=py36_0
  - sqlite=3.24.0=ha441bb4_0
  - tk=8.6.7=h35a86e2_3
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - pandas==0.23.4
    - python-dateutil==2.7.3
    - pytz==2018.5
    - six==1.11.0

